# (c) Copyright 2026 by Antony J Ingram of UNIVERSAL I.T SYSTEMS. All rights reserved.
# Licensed under the eCircuit Licence — see LICENCE.md.

"""Render a Circuit as a SPICE netlist."""

from __future__ import annotations

from .models import Circuit


def to_spice(circuit: Circuit) -> str:
    """SPICE netlist: title line, one card per component, .END."""
    lines = [f"* {circuit.name}"]
    if circuit.description:
        lines.append(f"* {circuit.description}")
    lines.append("* Generated by eCircuit Text2Circuit")
    for component in circuit.components:
        if component.pins:
            pin_map = " ".join(
                f"{pin.pin}:{pin.name}={pin.net}" for pin in component.pins
            )
            lines.append(f"* {component.ref} {component.value} pins: {pin_map}")
        card = [component.ref, *component.nodes]
        if component.value:
            card.append(component.value)
        lines.append(" ".join(card))
    lines.append(".END")
    return "\n".join(lines) + "\n"
