# (c) Copyright 2026 by Antony J Ingram of UNIVERSAL I.T SYSTEMS. All rights reserved.
# Licensed under the eCircuit Licence — see LICENCE.md.

"""Turn a Circuit into a runnable ngspice deck."""

from __future__ import annotations

import re

from ecircuit.text2circuit.models import Circuit, Component
from ecircuit.text2circuit.pinouts import lookup_pinout

from .models import (
    BJT_MODELS,
    DIODE_MODELS,
    bjt_model_for,
    diode_model_for,
    subckt_for_device,
)


class SimulationError(RuntimeError):
    """The circuit cannot be simulated, or ngspice failed."""


_VOLTS = re.compile(r"^(\d+(?:\.\d+)?)\s*V$", re.IGNORECASE)


def _source_value(value: str) -> str:
    """'9V' -> '9'; 'AC 1', 'DC 5', plain numbers pass through."""
    value = value.strip()
    if match := _VOLTS.match(value):
        return match.group(1)
    return value or "0"


def _card_name(prefix: str, ref: str) -> str:
    return ref if ref.startswith(prefix) else prefix + ref


def _ic_card(component: Component, models: dict[str, str]) -> str:
    subckt = subckt_for_device(component.value)
    if subckt is None:
        raise SimulationError(
            f"{component.ref}: no SPICE model for {component.value!r} yet — "
            "simulation supports the 555 family and dual op-amps so far"
        )
    name, definition = subckt
    models[name] = definition

    if not component.pins:
        raise SimulationError(
            f"{component.ref} ({component.value}): named pins are required for simulation"
        )
    by_number = {pin.pin: pin for pin in component.pins}
    pinout = lookup_pinout(component.value)
    size = len(pinout) if pinout else max(by_number)
    nets = []
    for number in range(1, size + 1):
        pin = by_number.get(number)
        # unconnected package pins get a private floating node
        nets.append(pin.net if pin else f"NC_{component.ref}_{number}")
    return f"{_card_name('X', component.ref)} {' '.join(nets)} {name}"


def _component_card(
    component: Component, models: dict[str, str], warnings: list[str]
) -> str | None:
    kind = component.type.lower()
    nodes = " ".join(component.nodes)

    if component.pins or kind == "ic":
        return _ic_card(component, models)
    if "resistor" in kind:
        return f"{_card_name('R', component.ref)} {nodes} {component.value}"
    if "capacitor" in kind:
        return f"{_card_name('C', component.ref)} {nodes} {component.value}"
    if "inductor" in kind:
        return f"{_card_name('L', component.ref)} {nodes} {component.value}"
    if "diode" in kind or "led" in kind:
        model = diode_model_for(component.value, kind)
        models[model] = DIODE_MODELS[model]
        return f"{_card_name('D', component.ref)} {nodes} {model}"
    if "transistor" in kind or "npn" in kind or "pnp" in kind:
        if len(component.nodes) != 3:
            raise SimulationError(f"{component.ref}: transistor needs exactly 3 nodes")
        model = bjt_model_for(component.value, kind)
        models[model] = BJT_MODELS[model]
        return f"{_card_name('Q', component.ref)} {nodes} {model}"
    if "battery" in kind or "voltage" in kind:
        return (
            f"{_card_name('V', component.ref)} {nodes} {_source_value(component.value)}"
        )
    if "current" in kind:
        return (
            f"{_card_name('I', component.ref)} {nodes} {_source_value(component.value)}"
        )
    if "switch" in kind:
        warnings.append(f"{component.ref}: switch treated as closed (1 ohm)")
        return f"{_card_name('R', component.ref)} {nodes} 1"
    if "connector" in kind:
        warnings.append(f"{component.ref}: connector left open (not simulated)")
        return None
    raise SimulationError(
        f"{component.ref}: don't know how to simulate component type {component.type!r}"
    )


def build_deck(circuit: Circuit, control_lines: list[str]) -> tuple[str, list[str]]:
    """Build an ngspice deck; returns (deck text, warnings)."""
    models: dict[str, str] = {}
    warnings: list[str] = []
    cards = []
    for component in circuit.components:
        card = _component_card(component, models, warnings)
        if card is not None:
            cards.append(card)

    lines = [f"* {circuit.name} — generated by eCircuit simulation"]
    lines.extend(cards)
    lines.extend(models.values())
    lines.append(".control")
    lines.append("set filetype=ascii")
    lines.extend(control_lines)
    lines.append("quit")
    lines.append(".endc")
    lines.append(".END")
    return "\n".join(lines) + "\n", warnings


def recordable_nets(circuit: Circuit) -> list[str]:
    """Nets worth recording: everything except ground."""
    return [net for net in circuit.nets if net != "0"]
