# (c) Copyright 2026 by Antony J Ingram of UNIVERSAL I.T SYSTEMS. All rights reserved.
# Licensed under the eCircuit Licence — see LICENCE.md.

import pytest
from pydantic import ValidationError

from ecircuit.text2circuit import (
    Circuit,
    CircuitParseError,
    Component,
    build_bom,
    parse_circuit_response,
    to_csv,
    to_markdown,
    to_spice,
)


@pytest.fixture
def divider() -> Circuit:
    return Circuit(
        name="voltage_divider",
        description="5V to 2.5V resistive divider",
        components=[
            Component(ref="V1", type="voltage_source", value="5", nodes=["VIN", "0"]),
            Component(ref="R1", type="resistor", value="10k", nodes=["VIN", "VOUT"]),
            Component(ref="R2", type="resistor", value="10k", nodes=["VOUT", "0"]),
        ],
    )


def test_ground_aliases_normalized() -> None:
    component = Component(ref="r5", type="resistor", value="1k", nodes=["gnd", "n1"])
    assert component.ref == "R5"
    assert component.nodes == ["0", "N1"]


def test_duplicate_refs_rejected() -> None:
    part = Component(ref="R1", type="resistor", value="1k", nodes=["A", "B"])
    with pytest.raises(ValidationError, match="duplicate reference designator"):
        Circuit(components=[part, part.model_copy()])


def test_nets_ground_first(divider: Circuit) -> None:
    assert divider.nets == ["0", "VIN", "VOUT"]


def test_spice_netlist(divider: Circuit) -> None:
    assert to_spice(divider) == (
        "* voltage_divider\n"
        "* 5V to 2.5V resistive divider\n"
        "* Generated by eCircuit Text2Circuit\n"
        "V1 VIN 0 5\n"
        "R1 VIN VOUT 10k\n"
        "R2 VOUT 0 10k\n"
        ".END\n"
    )


def test_bom_groups_identical_parts(divider: Circuit) -> None:
    lines = build_bom(divider)
    resistors = next(line for line in lines if line.type == "resistor")
    assert resistors.qty == 2
    assert resistors.refs == ["R1", "R2"]
    assert len(lines) == 2


def test_bom_renderers(divider: Circuit) -> None:
    lines = build_bom(divider)
    csv_text = to_csv(lines)
    assert csv_text.startswith("Qty,Type,Value,Part Number,References\n")
    assert "2,resistor,10k,,R1 R2" in csv_text
    markdown = to_markdown(lines)
    assert "| 2 | resistor | 10k |  | R1 R2 |" in markdown


def test_parse_tolerates_markdown_fences() -> None:
    raw = """```json
    {"name": "led", "components": [
      {"ref": "D1", "type": "led", "value": "red", "nodes": ["VCC", "N1"]},
      {"ref": "R1", "type": "resistor", "value": "330", "nodes": ["N1", "0"]}
    ]}
    ```"""
    circuit = parse_circuit_response(raw)
    assert circuit.name == "led"
    assert [component.ref for component in circuit.components] == ["D1", "R1"]


def test_parse_rejects_garbage() -> None:
    with pytest.raises(CircuitParseError):
        parse_circuit_response("sorry, I cannot design that circuit")
